export enum ICON_NAMES {
  add = 'add',
  arrowUp = 'arrow-up',
  arrowUpGreen = 'arrow-up-green',
  bell = 'bell',
  calendar = 'calendar',
  comment = 'comment',
  dasboard = 'dashboard',
  leaderboard = 'leaderboard',
  linkedIn = 'linked-in',
  moneyBillStack = 'money-bill-stack',
  phone = 'phone',
  pinterest = 'pinterest',
  schedule = 'schedule',
  setting = 'setting',
  shoppingBag = 'shopping-bag',
  twitter = 'twitter',
  video = 'video',
  viewList = 'view-list'
}
